// This code was largely generated by https://app.quicktype.io/ with a little bit of manual cleanup
export interface HoroscopeData {
  data: Data
  status: number
  success: boolean
}

export interface Data {
  date: string
  horoscope_data: string
}
